[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tutorial11"
version = "0.1.0"
description = "Tutorial 11: Built-in Tools & Grounding - Grounding Agent"
requires-python = ">=3.9"
dependencies = [
    "google-adk>=1.15.1",
]