[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tutorial05"
version = "0.1.0"
description = "Tutorial 05: Parallel Processing - Travel Planner Agent"
requires-python = ">=3.9"
dependencies = [
    "google-adk>=1.15.1",
]