[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tutorial01"
version = "0.1.0"
description = "Tutorial 01: Hello World Agent"
requires-python = ">=3.9"
dependencies = [
    "google-adk>=1.15.1",
]